# Site settings
name: Coco's Website
description: "A blog and a portfolio"
author: "Corinna Buerger"
title: "Python Implementations"
permalink: pretty
baseurl: /
url: https://corinnabuerger.github.io
# email: 

# social
github:
  username: CorinnaBuerger

twitter:
  username: coco_beatle

disqus:
  shortname: recursion-iteration
